#!/bin/bash

### ARCH SETUP ###
printf '%s\n\n\n## STARTING ARCH ##\n\n\n'
sleep 2

## EDIT
##(1) root
##(2) pacman
##(3) gpu
##(4) systemctl
##(5) user

ln -sf /usr/share/zoneinfo/Europe/London /etc/localtime
hwclock --systohc
timedatectl set-ntp true
sed -i '178s/.//' /etc/locale.gen
locale-gen
echo "LANG=en_US.UTF-8" >> /etc/locale.conf
echo "machine1" >> /etc/hostname
echo "127.0.0.1 localhost" >> /etc/hosts
echo "::1       localhost" >> /etc/hosts
echo "127.0.1.1 machine1.localdomain machine1" >> /etc/hosts
# ROOT
echo root:32435 | chpasswd

# PACMAN
pacman -S --noconfirm linux linux-firmware grub efibootmgr networkmanager

grub-install --target=x86_64-efi  --bootloader-id=grub_uefi --recheck
grub-mkconfig -o /boot/grub/grub.cfg

# GPU
#pacman -S xf86-video-intel
#pacman -S xf86-video-amdgpu
#pacman -S nvidia nvidia-utils nvidia-settings

# SYSTEMCTL
systemctl enable NetworkManager
#systemctl enable firewalld
#systemctl enable sshd
#systemctl enable reflector.service
#systemctl enable reflector.timer
#systemctl enable tlp
#systemctl enable acpid
#systemctl enable bluetooth

# USER
useradd -g wheel -m user1
echo user1:21324 | chpasswd
sed -i '85s/..//' /etc/sudoers

### DWM SETUP ###
printf '%s\n\n\n## STARTING DWM ##\n\n\n'
sleep 2

## EDIT
##(1) pacman
##(2) user: /home/(user1)/ - change user1

# PACMAN
pacman -S --noconfirm xorg-server xorg-xinit xorg-xsetroot xorg-xrandr htop neofetch firefox
printf '%s\n\n'
sleep 1

# USER
cp /etc/X11/xinit/xinitrc /home/user1/.xinitrc
sed -i '51s/./#t/;52s/./#x/;53s/./#x/;54s/./#x/;55s/./#e/' /home/user1/.xinitrc
echo '# execute' >> /home/user1/.xinitrc
echo 'exec dwm' >> /home/user1/.xinitrc

echo 'if [ -z "${DISPLAY}" ] && [ "${XDG_VTNR}" -eq 1 ]; then' >> /home/user1/.bash_profile
echo '        exec startx' >> /home/user1/.bash_profile
echo 'fi' >> /home/user1/.bash_profile

git clone https://git.suckless.org/dwm /home/user1/st
printf '%s\n\n'
git clone https://git.suckless.org/st /home/user1/dwm
printf '%s\n\n'
sleep 1
make clean install -C /home/user1/st
printf '%s\n\n'
make clean install -C /home/user1/dwm

chown -R user1 /home/user1
chgrp -R wheel /home/user1

printf '%s\n\n\n## DONE ##\n\n\n'
