#!/bin/bash

### ARCH SETUP ###
printf '%s\n\n\n## STARTING ARCH ##\n\n\n'
sleep 2

## EDIT
##(1) root
##(2) pacman
##(3) gpu
##(4) systemctl
##(5) user

ln -sf /usr/share/zoneinfo/Europe/London /etc/localtime
hwclock --systohc
timedatectl set-ntp true
sed -i '178s/.//' /etc/locale.gen
locale-gen
echo "LANG=en_US.UTF-8" >> /etc/locale.conf
echo "machine1" >> /etc/hostname
echo "127.0.0.1 localhost" >> /etc/hosts
echo "::1       localhost" >> /etc/hosts
echo "127.0.1.1 machine1.localdomain machine1" >> /etc/hosts
# ROOT
echo root:32435 | chpasswd

# PACMAN
pacman -S --noconfirm linux linux-firmware grub efibootmgr networkmanager

grub-install --target=x86_64-efi  --bootloader-id=grub_uefi --recheck
grub-mkconfig -o /boot/grub/grub.cfg

# GPU
#pacman -S xf86-video-intel
#pacman -S xf86-video-amdgpu
#pacman -S nvidia nvidia-utils nvidia-settings

# SYSTEMCTL
systemctl enable NetworkManager
#systemctl enable firewalld
#systemctl enable sshd
#systemctl enable reflector.service
#systemctl enable reflector.timer
#systemctl enable tlp
#systemctl enable acpid
#systemctl enable bluetooth

# USER
useradd -g wheel -m user1
echo user1:21324 | chpasswd
sed -i '85s/..//' /etc/sudoers
user=user1 #<--insert name

### DWM SETUP ###
printf '%s\n\n\n## STARTING DWM ##\n\n\n'
sleep 2

# PACMAN
pacman -S --noconfirm xorg-server xorg-xinit xorg-xsetroot xorg-xrandr htop xwallpaper neofetch vivaldi
printf '%s\n\n'
sleep 1

# COPY
cp /etc/X11/xinit/xinitrc /home/$user/.xinitrc
sed -i '51s/./#t/;52s/./#x/;53s/./#x/;54s/./#x/;55s/./#e/' /home/$user/.xinitrc
echo '# execute' >> /home/$user/.xinitrc
echo 'exec dwm' >> /home/$user/.xinitrc

# GIT
git clone https://git.suckless.org/dwm /home/$user/st
printf '%s\n\n'
git clone https://git.suckless.org/st /home/$user/dwm
printf '%s\n\n'
sleep 1
make clean install -C /home/$user/st
printf '%s\n\n'
make clean install -C /home/$user/dwm

# PERMISSION
chown -R user1 /home/$user
chgrp -R wheel /home/$user

printf '%s\n\n\n## DONE ##\n\n\n'
